### ISSUE TITLE
Request not sent to google

### ISSUE THREAD

**Issue by tohyung85** [aykutyaman/google-search#1]
Hi Aykutyaman,

I have tried using the google-search module as follows, however i am unable to get the search to be completed and hence get the callback function to work. 

Any advice?

`
'use strict';

var GoogleSearch = require('google-search');
var googleSearch = new GoogleSearch({
    key: "AXXXXXX-XXXXXXg",
    cx: "0XXXXXX:YYYYYY"
}); 

function ImgSearchHandler () {

```
this.retrieveSearchResults = function (req, res) {

    console.log("handler called");
    googleSearch.build({
      q: "",
      start: 5,
      fileType: "pdf",
      gl: "tr", //geolocation,
      lr: "lang_tr",
      num: 10, // Number of search results to return between 1 and 10, inclusive
      siteSearch: "http://kitaplar.ankara.edu.tr/" // Restricts results to URLs from a specified site
    }, function(error, response) {
      console.log(response);
    });

}
```

}

module.exports = ImgSearchHandler;
`

**Comment by tohyung85** [comment]
Issue lies with module google-search.js file:

`this._doRequest(this._generateUrl(options), callback);`

should not be commented,

`this._generateUrl(options);` 
should be commented out instead.

`
GoogleSearch.prototype.build = function(options, callback) {
  options = _.defaults(options, {
    fileType: "pdf"
  });
  //this._doRequest(this._generateUrl(options), callback); 
  this._generateUrl(options);
};
`

**Comment by kkobold** [comment]
I'v made a pull request. 
it´s fixed here if you need.

[https://github.com/kkobold/google-search](url)
