### ISSUE TITLE
fileType: pdf always added

### ISSUE THREAD

**Issue by kkobold** [aykutyaman/google-search#2]
Hi there.

`gs.build({
        q: 'kkobold',
        safe: "off",
        exactTerms: '"Belo Horizonte"',
        siteSearch: 'www.facebook.com'
    }, function(error, response) {
        console.log(response);
    });`

This code is also adding fileType:pdf. which is not necessay or desired. 

`GoogleSearch.prototype.build = function(options, callback) {
  options = _.defaults(options, {
    fileType: "pdf"
  });
  //this._doRequest(this._generateUrl(options), callback); 
  this._generateUrl(options);
};`

is adding it no matter what.

**Comment by aykutyaman** [comment]
@kkobold thanks you, I have accepted your pull request
